### ISSUE TITLE
To Fix array_merge(): Argument #1 is not an array laravel 5.4

### ISSUE THREAD

**Issue by karthiksk0062** [tzsk/sms#11] opened 2018-03-01 11:18 UTC
To Fix array_merge(): Argument #1 is not an array

please remove array_merge() functionality on Textlocal.php send() as it's the case which arises response as error on when the mobile number to send SMS is registered as dnd on Trai.
Code has to be changed as mentioned below
public function send()
{
$numbers = implode(",", $this->recipients);

    $response = $this->client->request("POST", $this->settings->url, [
        "form_params" => [
            "username" => $this->settings->username,
            "hash" => $this->settings->hash,
            "numbers" => $numbers,
            "sender" => urlencode($this->settings->sender),
            "message" => $this->body,
        ],
    ]);

    $data = $this->getResponseData($response);

    return (object) $data;
}
Note: As I am using this package on my Laravel project when vendor folder get updated error arises so to fix this issue please change as soon as possible

**Comment by tzsk** [comment] 2018-03-08 10:43
@karthiksk0062 Can you please provide me the dump (`dd`) of the `$data` variable? I am not being able to replicate the issue. For me it is working fine.

**Comment by tzsk** [comment] 2018-03-08 10:59
@karthiksk0062 Please update your package. I've released `V1.2.1`. And please confirm if the issue is fixed now. I'll reopen if it is not fixed.

**Closed by tzsk** 2018-03-08 10:59 UTC
